### ISSUE TITLE
Is there a way to use Rel=canonical tag for duplicate articles?

### ISSUE THREAD

**Issue by Djas2017** [Lednerb/bilberry-hugo-theme#154]
When I create an article-master for example and want to create another article called article-duplicate which contains a duplicated content.

From the seo perspective to keep blog crawling clean,  we need to add in the duplicate article a line:
<link rel="canonical" href="https://myblog-test.tld/gallery/article-master/" />

Ref: https://blog.alexa.com/canonical-url/

Is this something that already exist and can be done in an automatic way? Or we have to do it manually.

Example have a specific parameter "rel_canonical" when creating a new blog article where we specify:
`rel_canonical: 'https://myblog-test.tld/gallery/article-master/"'`
with the other parameters:
`title: ....`
`date: ...`
`categories: ...`
...

**Comment by Lednerb** [comment]
At the moment there is no such integration for this theme available.

After reading the linked article I would suggest to add both options: `rel_canonical` and `original_url` as parameters in the front matter. If one of these is set, the canonical url `link` tag will be set.

That's an easy integration.
Would be nice if you can send an PR, otherwise I will set it on my todo list.

**Comment by Djas2017** [comment]
If you can set it on your todo list, that will be great.
I have never sent a PR!
