### ISSUE TITLE
Add gitlab to social media footer urls

### ISSUE THREAD

**Issue by StevenDoesStuffs** [Lednerb/bilberry-hugo-theme#177]

**Comment by StevenDoesStuffs** [comment]
Really, the ability to add custom images with their own links for whatever social media site imaginable would be nice. It's quite impossible to cover all the possible things people might wanna link in that footer. For example, a gaming blog might wanna link their Steam account. People might wanna put a discord server, or a tech blog would want to put keybase, gpg stuff, etc.

**Comment by tonytheleg** [comment]
I too would love a gitlab option and since I've been using this theme for a class project, I'd like to offer taking on adding it if you are still looking. I agree that giving users an option to add some custom ones would be great too, if I can figure out the logistics of how to cleanly do that I'll shoot for that too. For now I was thinking I'd had some more common-but-not-so-common ones (like gitlab, keybase, steam, etc)

**Comment by Lednerb** [comment]
I thin the best way to implement this would be to have the option of defining the icon type (font-awesome list at the moment) and as an array in the `config.toml`.

The theme should then iterate over the given icons and links an render them in the footer.

With this approach we can directly support all pages and icons that are supported by fontawesome.

@tonytheleg PRs are welcome!

**Comment by tonytheleg** [comment]
That's what I was thinking as well, I'll play around with it and see if I can get it figured out.

**Comment by tonytheleg** [comment]
Sorry for delay, didn't realize the theme was pinned to Font Awesome 4.7 and realized that's why some custom icons I was trying would not work. I was playing around with what it would take to update to 5.11.2 which adds a lot more brand icons but never did quite get it working. I figured that was a separate PR on its own anyway with that many changes but probably worth looking into. A lot of sites like keybase, discord, and such are only available in the newer FA releases. Let me know if anything needs to be changed.
