### ISSUE TITLE
Translation missing for "estimated reading time" in several languages

### ISSUE THREAD

**Issue by enmanuelmoreira** [Lednerb/bilberry-hugo-theme#233]
Hi,
I enabled the parameter showReadingTime = true and the reading time doesn't show on the article bar

![Screenshot from 2020-08-01 14-20-33](https://user-images.githubusercontent.com/152518/89107908-47eda080-d402-11ea-86ba-c38a5f460d97.png)

The main language of the website is spanish (DefaultContentLanguage = "es")

It works with english only or with another language as well?

Regards.

**Comment by Lednerb** [comment]
Hi @enmanuelmoreira 

thanks for the bug report.
I've investigated the problem:

The language file does not contain the `readingTime` translations so an empty string is returned.

You can fix this by adding the following lines to the `i18n/es.toml` file and translate it accordingly:

https://github.com/Lednerb/bilberry-hugo-theme/blob/5333bbbec37ddebe6e1f0f0d6ccc42dfdbc29195/i18n/en.toml#L34-L36


I will rename this issue because the translation has to be added to other language files as well.

If you like, you can submit a PR for the Spanish language to be included in the theme.

**Comment by enmanuelmoreira** [comment]
PR sended. Thank you!

**Comment by enmanuelmoreira** [comment]
tested and it works!

**Comment by Lednerb** [comment]
I will leave this open to track the other missing languages.
