### ISSUE TITLE
Redirecting external links in new tab

### ISSUE THREAD

**Issue by anampopa** [Lednerb/bilberry-hugo-theme#273]
Great work with the bilberry theme. Very intuitive. I am using it to build a blog and I have a question. Should the hrefTargetBlank = true in config.toml do the job for redirecting external link in new tab?
I also tried [link](url){:target="_blank"} and embedding html syntax but this doesn't do the trick.
I try to do this in articles. What am I missing, can you please help me with this?

**Comment by igor-baiborodine** [comment]
Hi Ana,

RE: _Should the hrefTargetBlank = true in config.toml do the job for redirecting external link in new tab?_
It will not work. Since v0.62.0, Hugo switched to the Goldmark markdown renderer, which does support such behavior out of the box.
Therefore, since the BlackFriday renderer is no longer the default renderer, this configuration will be ignored.:
```toml
[blackfriday]
  hrefTargetBlank = false
```
For more details, please see this [thread](https://discourse.gohugo.io/t/how-to-open-link-in-new-tab-with-hugos-new-goldmark-markdown-renderer-in-v0-62-0/22540).

RE: _I also tried link{:target="_blank"} and embedding html syntax but this doesn't do the trick._
By default, the Goldmark renderer omits all raw HTML content embedded in the markdown.
To make it work, you should add the following to your `config.toml`:
```toml
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
```
For more details, please see this [thread](https://github.com/rstudio/blogdown/issues/447).

Cheers,

Igor

**Comment by igor-baiborodine** [comment]
Hi Ana,

The theme's config.toml file was updated with pull request https://github.com/Lednerb/bilberry-hugo-theme/pull/297.

I tested the raw HTML feature at [Bilberry Sandbox](https://www.bilberry-sandbox.kiroule.com/article/test-raw-html/).

Please see the corresponding [markdown file](https://github.com/igor-baiborodine/bilberry-hugo-theme-sandbox/blob/9226113d2aaec57002e1b7664f1fc547759dfc1c/content/article/test-raw-html.md). 

Cheers,

Igor
