### ISSUE TITLE
Make it possible to fix the site header when scrolling

### ISSUE THREAD

**Issue by tivasyk** [Lednerb/bilberry-hugo-theme#29]
An option somewhere in config.toml or CSS to fix the site header to prevent it from scrolling would be great.

**Comment by Lednerb** [comment]
When does the header scroll?
Do you mean vertically or horizontally?

On which device (dimensions) does the scrolling occur?

**Comment by tivasyk** [comment]
there's no error here, it's just a request for en improvement.

> _When does the header scroll? Do you mean vertically or horizontally?_ 
when the page is scrolled vertically; the header scrolls vertically with the page which is a normal behaviour.

> _On which device (dimensions) does the scrolling occur?_
eny device (well, i only checked on a notebook (2048x) and a smartphone (720x).

it would be great to have an option though to fix the header in place and not scroll it with the rest of the contents.

**Comment by Lednerb** [comment]
Now I thought about this option a lot ...

I don't think that this would be a feature the most users would ask for, and I would never use this because I love the integrated algolia search and for me, the `page`s are not very important (just an _Impress_ or _Contact me_ page). When using the algolia search, the space for pages is very limited.

So I think I would not implement this in the theme directly.
Maybe in the future, if many other people request for.

But I can help you, for your site:

- To archive a fixed navigation bar, you have to set the `permanentTopNav` option to `true`.

- After that, follow the instructions for [Custom colors and fonts](https://github.com/Lednerb/bilberry-hugo-theme#custom-colors-and-fonts).

- open the `themes/bilberry-hugo-theme/src/scss/_topnav.scss` file and [modify this part](https://github.com/Lednerb/bilberry-hugo-theme/blob/master/src/scss/_topnav.scss#L26-L28) to the following: 

```scss
&.permanentTopNav {    
    display: block;
    position: fixed;
    width: 100%;
    z-index: 60;
}
```

- Finally, you have to modify the `src/scss/_header.scss` file:

```scss
header {
    background-color: $base-color;
    color: $header-text-color;
    height: 20rem;
    display: flex;
    align-items: center;

    padding-top: 65px; // add this line

   ...
```

- As the last step, run `yarn run production` inside the theme's `src` folder.


That should do the trick ;-)

_Note:_ When you're upgrading my original theme (`Lednerb/bilberry-hugo-theme`) you have to apply these changes again. You can also fork this repository to your own namespace, do the changes there and merge newer versions of my theme to your customized version and then update from there.

**Comment by anoff** [comment]
I would like this feature as well 😁 Maybe like [beautiful jekyll](https://deanattali.com/beautiful-jekyll/) that the navbar actually shrinks and just leaves the _home button_ there. I find it hard to scroll up especially on mobile.
An alternative would be one of those navs that scrolls out but if you scroll up it immediatly pops into view (sorry don't know their name)

**Comment by igor-baiborodine** [comment]
@LITUATUI, the `stickyNav` parameter depends on the `permanentTopNav`. To make it the default behavior, the `permanentTopNav` parameter is to be set to `true` by default. I updated the [Features/Top Navigation Bar](https://github.com/Lednerb/bilberry-hugo-theme#top-navigation-bar) section in the `README`:

![image](https://user-images.githubusercontent.com/1027701/218101960-138988de-039e-4388-a8fb-0e2b13be9035.png)
