### ISSUE TITLE
Relative path to featured image in page bundle not working

### ISSUE THREAD

**Issue by metbril** [Lednerb/bilberry-hugo-theme#414]
I use page bundles for my articles. The featured image is applied through front matter. The theme currently supports this with the `featuredImage` front matter parameter.

When adding the front matter, my featured image is not shown as expected.

Both `featuredImage: some-image.jpg` and `featuredImage: ./some-image.jpg` are rendered as `<img src="/some-image.jpg" alt="">`.

My expectation is, that the path is rendered as specified, so `<img src="some-image.jpg" alt="">` and `<img src="./some-image.jpg" alt="">` respectively.

**Comment by igor-baiborodine** [comment]
@metbril, could you please confirm that the main issue here is that the featured image, defined via the front matter variable `featuredImage` with a relative path in a page bundle, is not shown **at all**?

**Comment by igor-baiborodine** [comment]
@metbril, in README, I added a new section named [Featured Image](https://github.com/Lednerb/bilberry-hugo-theme/tree/update-readme#featured-image):

![image](https://user-images.githubusercontent.com/1027701/181825178-e936a49c-3ca0-4472-9328-5e1016901c10.png)

In your case, the image path is not relative to the base URL. That's why it is not working. When using the page bundle, you can use the `featuredImage` front matter variable, but in this case, the featured image will not be cropped and resized.

Please see these test articles I created back then on the Bilberry Sandbox:
* Article 1
  https://github.com/igor-baiborodine/bilberry-hugo-theme-sandbox/tree/master/content/article/test-featured-image-resizing
  https://www.bilberry-sandbox.kiroule.com/article/test-featured-image-resizing/

* Article 2
  https://github.com/igor-baiborodine/bilberry-hugo-theme-sandbox/tree/master/content/article/test-featured-image-resizing-via-front-matter
  https://www.bilberry-sandbox.kiroule.com/article/test-featured-image-resizing-via-front-matter/

**Comment by igor-baiborodine** [comment]
@metbril, you can read more on the `relUrl` function [here](https://gohugo.io/functions/relurl/).

As for the relative URLs in your particular case, you can set the `relativeUrls` property to `true` in your configuration file to rewrite all relative URLs to be relative to the current content. Here is the Hugo [documentation](https://gohugo.io/functions/relurl/) on this property. 

I made a quick test in my local dev with the Bilberry Sandbox:
![image](https://user-images.githubusercontent.com/1027701/182046466-3c2b5813-b8b5-434c-824f-15e202f831d1.png)

![image](https://user-images.githubusercontent.com/1027701/182046498-508001f6-d53b-4de2-96aa-3ee9e81670f4.png)

![image](https://user-images.githubusercontent.com/1027701/182046519-927c9d84-daba-422c-91c9-0a39316fb3f8.png)

I'm moving this issue to Discussions since it's can be useful for other users.
