### ISSUE TITLE
Automatic algolia index update by golang cli app

### ISSUE THREAD

**Issue by rabarar** [Lednerb/bilberry-hugo-theme#43]
I wrote a quick algolia API to take the index.json file and update the algolia account. If anyone's interested, I can create a quick public repo and leave a link. I use this in my production push when I add content to my blog.

**Comment by Lednerb** [comment]
Hey, cool!

Can this CLI app be used for the complete setup or just for updating the index?
Does it copy the generated `public/index.json` to the account or does it generate the index on its own?

**Comment by rabarar** [comment]
Once you have an account, the cli updates the index by passing in the login credentials, index name, and json file as command-line parameters.

**Comment by Lednerb** [comment]
Okay, I've thought about this option for a while now...

Your go cli program runs without any dependencies?
What do you think about optimizing it, so that the program ships within the bilberry exampleSite, so it gets copied to the hugo project directory.

From that place, it could read the `config.toml` file for the algolia keys?
So maybe we can integrate this as simple as `./update-algolia` or something like that?

A zero-config algolia integration would be really really cool.

The only _problem_ is how to save the algolia secret key when using the site with `git` because at the moment you can commit and upload the `config.toml` file without any problems but the algolia secret key should stay secret.

Although it's maybe not the best idea to publish the hole hugo project directory when using the draft functionality etc.

What do you think about it ?

**Comment by rabarar** [comment]
@Lednerb the only dependency is the "github.com/algolia/algoliasearch-client-go/algoliasearch" to access the algolia API.  We can definitely add it to the example site. I've wrapped it with shell script that parses the config.toml file and extracts the algolia info. The only user-supplied info required is the algolia private key. Because all of the keys aren't self-contained in the config.toml, making it self-contained would be difficult. If however, we modify the script to contain both public and private algolia keys, the user would only need to build the go binary to use the update shell script and api access program.

**Comment by Lednerb** [comment]
@rabarar 
> The only user-supplied info required is the algolia private key. Because all of the keys aren't self-contained in the config.toml, making it self-contained would be difficult. 

You don't need the `index` or `app_id` infos?


> If however, we modify the script to contain both public and private algolia keys, the user would only need to build the go binary to use the update shell script and api access program.

Is there a possibility to ship a pre-built update tool that reads the `config.toml` by itself?
Hugo is so cool because it's only one binary file that does all the _magic_.
I'd like to aware the users of self-building the updater, installing golang and needed dependencies.

**Comment by taivu** [comment]
Not saying we should ditch algoria, but has Lunr been considered? https://lunrjs.com/ ive seen it implemented in another hugo theme, where Hugo is also generating JSON alongside with html, and the JSON is hooked up with Lunr for searching.

**Comment by Lednerb** [comment]
@rabarar any news on this yet?

**Comment by rabarar** [comment]
I ran into free-usage limits with algolia, but I'll add a repo of what I wrote and send you a link in case others find the service useful.

**Comment by rabarar** [comment]
Here’s the repo I added with the code:

https://github.com/rabarar/hugo-algolia <https://github.com/rabarar/hugo-algolia>

**Comment by Lednerb** [comment]
Done via python script.

Check the readme for further information:
https://github.com/Lednerb/bilberry-hugo-theme#Update-the-search-index
